
export enum AssetType {
    ActionPlan    = "Action plan",
    Animation     = "Animation",
    Appointment   = "Appointment",
    Article       = "Article",
    Assessment    = "Assessment",
    Audio         = "Audio",
    Biometrics    = "Biometrics",
    Challenge     = "Challenge",
    Checkup       = "Checkup",
    Consultation  = "Consultation",
    Exercise      = "Exercise",
    Goal          = "Goal",
    Infographics  = "Infographics",
    Medication    = "Medication",
    Meditation    = "Meditation",
    Message       = "Message",
    Nutrition     = "Nutrition",
    Physiotherapy = "Physiotherapy",
    Priority      = "Priority",
    Reflection    = "Reflection",
    Reminder      = "Reminder",
    Video         = "Video",
    WebLink       = "Web link",
    WebNewsfeed   = "Web newsfeed",
    WordPower     = "Word power"
}

export const AssetTypeList: AssetType[] = [
    AssetType.ActionPlan,
    AssetType.Animation,
    AssetType.Appointment,
    AssetType.Article,
    AssetType.Assessment,
    AssetType.Audio,
    AssetType.Biometrics,
    AssetType.Challenge,
    AssetType.Checkup,
    AssetType.Consultation,
    AssetType.Exercise,
    AssetType.Goal,
    AssetType.Infographics,
    AssetType.Medication,
    AssetType.Meditation,
    AssetType.Message,
    AssetType.Nutrition,
    AssetType.Physiotherapy,
    AssetType.Priority,
    AssetType.Reflection,
    AssetType.Reminder,
    AssetType.Video,
    AssetType.WebLink,
    AssetType.WebNewsfeed,
    AssetType.WordPower,
];

export enum TimeSlot {
    EarlyMorning  = "Early morning",
    Morning       = "Morning",
    Afternoon     = "Afternoon",
    LateAfternoon = "Late afternoon",
    Evening       = "Evening",
    Night         = "Night",
    LateNight     = "Late night",
    Unspecified   = "Unspecified",
    WholeDay      = "Whole day"
}

export const TimeSlotList: TimeSlot[] = [
    TimeSlot.EarlyMorning,
    TimeSlot.Morning,
    TimeSlot.Afternoon,
    TimeSlot.LateAfternoon,
    TimeSlot.Evening,
    TimeSlot.Night,
    TimeSlot.LateNight,
    TimeSlot.Unspecified,
    TimeSlot.WholeDay,
];

export const AssetTypeCodePrefixes = {
    "Action plan"   : "ACTNPLAN",
    "Animation"     : "ANIMTION",
    "Appointment"   : "APPNTMNT",
    "Article"       : "ARTICLE",
    "Assessment"    : "ASSESMNT",
    "Audio"         : "AUDIO",
    "Biometrics"    : "BIOMTRIC",
    "Challenge"     : "CHALLNGE",
    "Checkup"       : "CHECKUP",
    "Consultation"  : "CONSLTTN",
    "Exercise"      : "EXERCISE",
    "Goal"          : "GOAL",
    "Infographics"  : "INFGRPHC",
    "Medication"    : "MEDICATN",
    "Meditation"    : "MEDITATN",
    "Message"       : "MESSAGE",
    "Nutrition"     : "NUTRITON",
    "Physiotherapy" : "PHYSTHRP",
    "Priority"      : "PRIORITY",
    "Reflection"    : "REFLECTN",
    "Reminder"      : "REMINDER",
    "Video"         : "VIDEO",
    "Web link"      : "WEBLINK",
    "Web newsfeed"  : "NEWSFEED",
    "Word power"    : "WORDPOWR",
};
